EXCHANGE_COINHAKO = :coinhako
EXCHANGE_BINANCE_SG = :binance_sg
EXCHANGE_GEMINI = :gemini

EXCHANGES = [
  EXCHANGE_BINANCE_SG,
  EXCHANGE_COINHAKO,
  EXCHANGE_GEMINI,
]

TRANSACTION_TYPE_BUY = :buy
TRANSACTION_TYPE_SELL = :sell
TRANSACTION_TYPE_SEND = :send
TRANSACTION_TYPE_RECV = :recv
